playbooks/roles/sysdig/defaults/main.yml, playbooks/roles/sysdig/tasks/main.yml
=> Adds sysdig cli role

playbooks/Makefile, playbooks/inventory, playbooks/monitoring.yml
Also adds a basic makefile for calling the playbooks.
This should be replaced by a proper CLI down the road.
@mrgnr This should help streamline the customer installments for the time being. We might have to rename some folders in the various repos so that they're consistent. The makefile is only temporary until we build a proper cli tool.
=> Adds monitoring playbooks and dynamic inventory

.gitignore, playbooks/roles/nginx/defaults/main.yml, playbooks/roles/nginx/tasks/main.yml, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms-preview.j2, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/static-files.j2
Adds hooks for location and http block includes in lms.j2, lms-preview.j2, cms.j2 nginx role templates, and location includes in static_files.j2 template.
Also parameterizes cms and lms max upload size and proxy read timeouts.
=> Nginx includes hooks

vagrant/release/devstack/Vagrantfile.dogwood
Adding Vagrantfile for the dogwood devstack. This is to accompany the dogwood devstack install instructions per https://trello.com/c/Kjyv04Sg
=> Added Vagrantfile for dogwood devstack

vagrant/release/devstack/Vagrantfile.eucalyptus
to run Eucalyptus devstack for Appsembler version.
See trello card for additional information: https://trello.com/c/OvoHEbWt
=> Added Vagrantfile.eucalyptus 

playbooks/appsemblerPlaybooks/eucalyptus_pro_server.yml, playbooks/roles/mongo/defaults/main.yml, playbooks/roles/mongo/templates/mongodb.conf.j2
This PR contains the first version of our eucalyptus pro deployment.
=> eucalyptus pro deploy playbook

playbooks/eucalyptus_basic_server.yml
This PR includes all the new changes (Mongo auth, stack driver, secure passwords for MySQL and Mongo) implemented in pro and enterprise, but applied to our basic playbook.
=> Eucalyptus basic fixes

playbooks/edx-east/edxapp.yml, playbooks/roles/scorm/meta/main.yml, playbooks/roles/scorm/tasks/main.yml, playbooks/roles/scorm/tasks/scorm_backup.yml, playbooks/roles/scorm/tasks/scorm_base.yml, playbooks/roles/scorm/tasks/scorm_players.yml
when conditionals don't work for entire roles in ansible<2 so this reworks how inclusion of various parts of the SCORM setup are done.
=> Rework scorm role so it can be properly skipped

playbooks/appsemblerPlaybooks/ficus_basic.yml, playbooks/appsemblerPlaybooks/ficus_enterprise.yml, playbooks/appsemblerPlaybooks/ficus_pro.yml
Basic, Pro, and Enterprise tiers.
=> Add Ficus playbooks

CHANGELOG.md, playbooks/roles/analytics_pipeline/tasks/main.yml, playbooks/roles/edxapp/defaults/main.yml, playbooks/roles/edxapp/templates/cms_gunicorn.py.j2, playbooks/roles/edxapp/templates/lms_gunicorn.py.j2, playbooks/roles/hadoop_common/defaults/main.yml, playbooks/roles/hadoop_common/tasks/main.yml, playbooks/roles/hadoop_common/templates/etc/systemd/system/hdfs-datanode.service.j2, playbooks/roles/hadoop_common/templates/etc/systemd/system/hdfs-namenode.service.j2, playbooks/roles/hadoop_common/templates/etc/systemd/system/mapreduce-historyserver.service.j2, playbooks/roles/hadoop_common/templates/etc/systemd/system/yarn-nodemanager.service.j2, playbooks/roles/hadoop_common/templates/etc/systemd/system/yarn-proxyserver.service.j2, playbooks/roles/hadoop_common/templates/etc/systemd/system/yarn-resourcemanager.service.j2, playbooks/vagrant-analytics.yml, vagrant/base/analyticstack/Vagrantfile, vagrant/base/fullstack/Vagrantfile, vagrant/release/analyticstack/Vagrantfile, vagrant/release/devstack/Vagrantfile, vagrant/release/fullstack/Vagrantfile
I've pulled in changes from Ficus.3 into our Ficus configuration branch. Please review ASAP, we'll need it for deploying Tahoe Ficus on Thursday. Most changes are related to analytics devstack so it shouldn't be a big deal. [Release notes here](https://groups.google.com/forum/#!topic/openedx-ops/6zsfCPq5_Ac)
---
=> Appsembler/feature/merge ficus.3

playbooks/appsemblerPlaybooks/update_theme.yml
This is still a work in progress, but it's functioning as is for now.
Things I still need to add:
=> [WIP] playbook to update our customer specific themes for edx-platform

playbooks/appsemblerPlaybooks/monitoring.yml
Related:
- https://github.com/appsembler/roles/pull/15
- https://github.com/noderabbit-team/edx-configs/pull/88
=> Use monit for monitoring on Azure

playbooks/appsemblerPlaybooks/update_theme.yml
Pulled the update_theme.yml playbook from appsembler/eucalyptus/develop and updated the 'git' task name from `git_2_0_1` to `git`
=> Adding update_theme.yml playbook to ficus

playbooks/appsemblerPlaybooks/monitoring.yml
Adding New Relic to monitoring.yml playbook.
=> include newrelic in monitoring.yml

playbooks/roles/postgresql_aggregation/defaults/main.yml, playbooks/roles/postgresql_aggregation/tasks/main.yml
This PR is a follow up of https://github.com/appsembler/configuration/pull/85
=> [Ficus] TLS support for aggreagtion psql db

playbooks/eucalyptus_basic_server.yml
Just needed a condition on the role
=> eucalyptus_basic_server playbook demo role obey INSTALL_DEMO_DATA

playbooks/appsemblerPlaybooks/ficus_basic.yml, playbooks/appsemblerPlaybooks/ficus_enterprise.yml, playbooks/appsemblerPlaybooks/ficus_pro.yml, playbooks/roles/ecommerce_theme/defaults/main.yml, playbooks/roles/ecommerce_theme/tasks/main.yml
=> ecommerce theme role

vagrant/release/devstack/Vagrantfile
=> Added Vagrantfile specific to ficus

playbooks/roles/githubsshkeys/tasks/main.yml
=> install pyOpenSSL and fix githubsshkeys_usernames issue

playbooks/roles/jenkins_configuration/templates/emr-vars.yml.j2
@tkeemon The EMR sec group is being hardcoded, this PR fixes the issue adding the value from the configuration.
=> fix emr sec group hardcoded

playbooks/appsemblerPlaybooks/intersystems.yml
... these changes are actually quite old, but the PR was done against `appsembler/master`.  `appsembler/feature/mergeDogwood.3` is our de-facto "appsembler/dogwood/master" so I'm merging to that instead.
=> Update intersystems custom playbook

playbooks/appsemblerPlaybooks/update_custom_requirements.yml
- update private Python requirements
- update extra Python requirements
- delete static assets dirs
- collect static assets for service variants
- restart LMS, CMS, workers
=> playbook to update custom requirements

playbooks/roles/edx_ansible/templates/server_vars.j2
=> add new vars to edx ansible server vars

playbooks/appsemblerPlaybooks/update_custom_requirements.yml
Just bringing it forward from Ficus
=> update_custom_requirements.yml playbook for Ginkgo

playbooks/roles/nginx/defaults/main.yml, playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
=> Add nginx_map_hash_bucket_size variable

playbooks/roles/custom_domains/tasks/main.yml, playbooks/roles/edx_ansible/templates/server_vars.j2
---
This PR is a companion for: https://github.com/appsembler/roles/pull/46 and https://github.com/appsembler/tahoe_cert_agent/pull/2
=> Set var to run lets encrypt isolated
