appsembler/configuration

playbooks/roles/stackdriver/defaults/main.yml, playbooks/roles/stackdriver/handlers/main.yml, playbooks/roles/stackdriver/tasks/main.yml, playbooks/roles/stackdriver/templates/stackdriver-agent
This role installs and configures the Stackdriver agent. If deployed on GCP, setting `stackdriver_detect_gcm: "yes"` (which is default) should allow the agent to talk to Google Cloud Monitoring without further configuration. Otherwise, the `stackdriver_api_key` (found in the Stackdriver account settings) can be specified.
=> Add stackdriver role

playbooks/mysql_init.yml, playbooks/roles/mysql_init/defaults/main.yml, playbooks/roles/mysql_init/tasks/main.yml
This role configures a remote MySQL instances, such as Google Cloud SQL. It creates the same users and tables as the [edxlocal](https://github.com/appsembler/configuration/tree/appsembler/master/playbooks/roles/edxlocal) role, but additional parameters are added to each task to specify the database host and login credentials.
To configure a remote MySQL instance, the `mysql_init.yml` playbook can be run locally:
```
ansible-playbook -i localhost, -c local mysql_init.yml -e @my-vars.yml
```
=> Add mysql_init role

playbooks/roles/backups/tasks/main.yml, playbooks/roles/backups/templates/backup.py
The maximum file size for a single-PUT upload is 5GB. We now break files into 100MB chunks and perform a multipart upload. The chunks are reassembled by S3 into a single file once the upload completes. See [Storing Large Data](https://boto.readthedocs.io/en/latest/s3_tut.html#storing-large-data).
=> Use multipart uploads for backups to S3

.gitignore, docker/build/course_discovery/Dockerfile, docker/build/course_discovery/ansible_overrides.yml, docker/build/course_discovery/inventory, playbooks/Makefile, playbooks/amc.yml, playbooks/appsembler/scripts/check_git_is_up2date.sh, playbooks/mongo_replicaset.yml, playbooks/mysql_init.yml, playbooks/roles/edxapp/tasks/service_variant_config.yml, playbooks/roles/mongo_3_0/templates/repset_add_secondaries.js.j2, playbooks/roles/mysql_init/defaults/main.yml, playbooks/roles/mysql_init/tasks/main.yml, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/insights.j2, playbooks/roles/oauth_client_setup/tasks/main.yml, playbooks/roles/scorm/tasks/main.yml, playbooks/roles/server_utils/meta/main.yml, playbooks/testdrive.yml, util/vpc-tools/abbey.py, vagrant/release/devstack/Vagrantfile.amc
There were are lot of commits not in appsembler/master that were in amc and testdrive branches but likely that's because we cherry picked those from somewhere. There were not conflicts other than in our own files which I think I've resolved.
This allows us deploy testdrive and AMC from appsembler/master and not have to have diffferent branches for each of those. AMC and testdrive should converge into a single THING sometime soon but since they are 2 different entities now it makes sense to have 2 different playbooks.
See Makefile for invocation instructions and how to deploy to either of those (AMC or testdrive).
Hopefully the naming is cleared up now.
Pair PR is in the edx-configs repo here: https://github.com/noderabbit-team/edx-configs/pull/7
=> Refactors testdrive vs. amc stuff and merges into appsembler/master

playbooks/appsemblerPlaybooks/dogwood_multiserver_deploy.yml, playbooks/appsemblerPlaybooks/dogwood_multiserver_deploy_cloud_sql.yml, playbooks/appsemblerPlaybooks/multiserver_deploy.yml, playbooks/roles/backups/defaults/main.yml, playbooks/roles/backups/files/backup.py, playbooks/roles/backups/tasks/main.yml
When backups fail, they aren't properly cleaned up and accumulate on disk. In addition, we have no way of knowing until the disk fills up and we receive an disk space alert. This PR ensures that backups are deleted from the disk and that Sentry is triggered when a backup fails.
=> Clean up and alert Sentry on backup failures

playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms-preview.j2, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/static-files.j2
@denibertovic @bezidejni 
Please review this ASAP, in the las merged PR #22 we lost some @bryanlandia changes related to extra nginx rules. We are actively using this in at least 3 customers.
=> re-apply @bryanlandia changes for allow extra nginx rules.

playbooks/roles/backups/files/backup.py
The `--delete-ghost-migrations` flag is specific to South and doesn't exist in Django 1.8+.
The `--no-compress` flag has been renamed to `--uncompressed` and can now be used to restore backups from non-compressed files.
=> Remove --delete-ghost-migrations flag; restore non-compressed backups

playbooks/appsemblerPlaybooks/eucalyptus_enterprise_deploy.yml, playbooks/roles/mongo_3_0/tasks/main.yml, playbooks/roles/mysql_init/defaults/main.yml
Here is the new playbook for enterprise deploys, with a fix for mongo 3 (we need mongo 3 for the replica set) and mysql_init vars for a new edxapp mysql table in eucalyptus.
=> enterprise tier playbook, mongo 3 fix, mysql new table fix

playbooks/roles/mysql_init/defaults/main.yml, playbooks/roles/mysql_init/tasks/main.yml
Services running as `www-data` and management commands running as `edxapp` need to be able to read TLS certs. By default, the owner of the certs is now `edxapp` and the group is `www-data`. Both owner and group have read-only permissions.
=> Change permissions for MySQL TLS certs

playbooks/roles/mysql_init/tasks/main.yml
Several users need read access to the certs to run migrations. Unfortunately, it's not straightforward to give only those users access to the certs in the configuration repo. While not ideal, I don't consider this a major security issue since users still need credentials to access the database and TLS isn't (currently) strictly required to connect.
=> Make TLS certs for MySQL world-readable

playbooks/roles/mysql_init/defaults/main.yml
The `edxapp` user may not exist on every server, but `{{ common_web_user }}` (aka `www-data`) does. A [previous PR](https://github.com/appsembler/configuration/pull/51) changes the cert permissions to 0444, so other users like `edxapp` and `xqueue` will still be able to read them.
=> Change owner of MySQL certs to `common_web_user`

playbooks/roles/nginx/defaults/main.yml, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
The GCP HTTP(S) load balancer will only forward requests to healthy nodes. For a node to be considered healthy it must return a 200 status code. This PR allows us to return 200 based on the user agent.
When using a GCP load balancer, we need to set:
- `NGINX_HEALTH_CHECK_ENABLED: True`
- `NGINX_HEALTH_CHECK_USER_AGENT: "GoogleHC/1.0"`
=> Add nginx health check for LMS

playbooks/appsemblerPlaybooks/dogwood_multiserver_deploy.yml, playbooks/appsemblerPlaybooks/dogwood_multiserver_deploy_cloud_sql.yml, playbooks/appsemblerPlaybooks/eucalyptus_enterprise_deploy.yml, playbooks/appsemblerPlaybooks/eucalyptus_pro_server.yml, playbooks/appsemblerPlaybooks/multiserver_deploy.yml, playbooks/roles/edxapp/defaults/main.yml, playbooks/roles/edxapp/tasks/service_variant_config.yml, playbooks/roles/mongo_3_0/defaults/main.yml, playbooks/roles/mongo_3_0/tasks/main.yml, playbooks/roles/mongo_3_0/templates/mongod.conf.j2, playbooks/roles/mongo_3_0/templates/mongodb-standalone.conf.j2
This PR supports enabling TLS for connections to Mongo3. To enable TLS on the Mongo side, set `MONGO_SSL_MODE: "allowSSL"`. TLS can be forced with `MONGO_SSL_MODE: "requireSSL"`, but shouldn't be used until the forum supports TLS connections to Mongo. When TLS is enabled, a CA certificate must be provided (`MONGO_SSL_CA_CERT`), along with a server key (`MONGO_SSL_SERVER_KEY`) and server cert (`MONGO_SSL_SERVER_CERT`) signed by the provided CA.
The LMS/CMS can connect to Mongo3 over TLS by setting `EDXAPP_MONGO_USE_SSL: True` and providing a CA cert and client key/cert. The CA cert must be the same one used to sign the Mongo
server cert and the client cert. When TLS is enabled, `EDXAPP_MONGO_SSL_CLIENT_CERT_PATH` and `EDXAPP_MONGO_SSL_CA_CERT_PATH` must be set to the paths where the client …
=> Support TLS for Mongo3

playbooks/roles/analytics_api/templates/edx/app/supervisor/conf.d.available/analytics_api.conf.j2, playbooks/roles/certs/templates/certs.conf.j2, playbooks/roles/common_vars/defaults/main.yml, playbooks/roles/ecommerce/templates/edx/app/supervisor/conf.d.available/ecommerce.conf.j2, playbooks/roles/ecomworker/templates/edx/app/supervisor/conf.d.available/ecomworker.conf.j2, playbooks/roles/edx_notes_api/templates/edx/app/supervisor/conf.d.available/edx_notes_api.conf.j2, playbooks/roles/edxapp/templates/cms.conf.j2, playbooks/roles/edxapp/templates/lms.conf.j2, playbooks/roles/edxapp/templates/workers.conf.j2, playbooks/roles/forum/templates/forum.conf.j2, playbooks/roles/insights/templates/edx/app/supervisor/conf.d.available/insights.conf.j2, playbooks/roles/programs/templates/edx/app/supervisor/conf.d.available/programs.conf.j2, playbooks/roles/xqueue/templates/xqueue.conf.j2, playbooks/roles/xqwatcher/templates/edx/app/supervisor/conf.d/xqwatcher.conf.j2
Not sure why, but default edx configuration does not set up Supervisor to restart programs which fail unexpectedly.  This PR sets autorestart  to 'unexpected', and sets common defaults for number of start attempts and number of seconds a program must stay up to count as started.  
cc @natea
=> Auto restart for Supervisor programs when unexpected failure 

playbooks/roles/backups/files/backup.py
Sentry only triggers PagerDuty alerts once for each [group](https://github.com/getsentry/sentry-plugins/blob/d4583befd3411d23763db94e5e9e8e20c9c28711/src/sentry_plugins/pagerduty/plugin.py#L59) of events. We want to send a new PagerDuty alert on every backup failure. Passing a unique [fingerprint](https://raven.readthedocs.io/en/stable/advanced.html#custom-grouping-behavior) every time `captureException()` is called ensures that the error will be assigned a new group in Sentry, resulting in a PagerDuty alert.
=> Use unique fingerprint for every backup failure

playbooks/amc.yml
This is needed to copy MySQL TLS certs.
Also replaced the deprecated `sudo: True`.
=> Call mysql_init role from AMC playbook

playbooks/appsemblerPlaybooks/monitoring.yml
We now use monit to [check static assets](https://github.com/appsembler/roles/pull/16) on all platforms.
=> Always run monit role

playbooks/roles/edxapp/templates/edx/bin/edxapp-migrate-cms.j2, playbooks/roles/edxapp/templates/edx/bin/edxapp-migrate-lms.j2
This PR excludes `appsembler_usage ` database from the migrations scripts, so the migration doesn’t fail for installations without `appsembler_usage defined.
=> Exclude `appsembler_usage` frommigrations scripts

playbooks/roles/nginx/templates/edx/app/nginx/sites-available/nginx_redirect.j2
This addresses the case where we need to redirect from one domain with an SSL cert to another domain with a different SSL cert, where both certs are on the server where Nginx is running.  This allows you to use the `nginx_redirect.j2` templates for the `nginx` role, but specify SSL cert and key for each redirecting domain.
=> Allow separate SSL cert/key for Nginx redirect template

playbooks/appsemblerPlaybooks/eucalyptus_enterprise_deploy.yml, playbooks/appsemblerPlaybooks/eucalyptus_pro_server.yml, playbooks/eucalyptus_basic_server.yml
We need the option to re-enable New Relic for some of our customer deployments (Trinity). I think this is the best way to handle it in Eucalyptus. In Ficus I'll add it to the monitoring.yml playbook. 
Thoughts?
=> add new relic back to eucalyptus playbooks

playbooks/roles/nginx/defaults/main.yml, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
For some customers, with integrations with other systems and SSO specially, we need to add extra rules on their nginx configuration, in order to hide and redirect paths to other systems in their architecture.
The old solution developed for Dogwood, consisted in store these rules in separate files, in our configs repo, checkout the files into the `sites-avalaible` dir, and include them on the `lms` and `cms` configs.
This doesn't work anymore, since we don't run ansible inside the customer VM anymore, so this change basically changes the file include on the Nginx configs, for variable include. 
To store these rules into the server-vars files isn't ideal, because it can get large, but in a second stage, we should move those variable contents to files, stored on edx-configs, and in ax, add …
=> new nginx role variables for extra http rules.

playbooks/appsemblerPlaybooks/ficus_basic.yml, playbooks/appsemblerPlaybooks/ficus_enterprise.yml, playbooks/appsemblerPlaybooks/ficus_insights.yml, playbooks/appsemblerPlaybooks/ficus_pro.yml
This PR adds tags to each role in the ficus playbooks. When a tag is applied to a role in a playbook, the tag is [inherited](https://docs.ansible.com/ansible/latest/playbooks_tags.html#tag-inheritance) by all tasks in that role and its dependencies.
For example, to run only the `xqueue` role and its dependencies, run
```
$ ansible-playbook -i path/to/inventory --tags xqueue ficus_pro.yml
```
You can check which tasks will be run for a tag using `--list-tasks`:
```
$ ansible-playbook -i path/to/inventory --list-tasks --tags xqueue ficus_pro.yml
```
=> Apply role tags in ficus playbooks

playbooks/amc.yml, playbooks/roles/custom_domains/meta/main.yml, playbooks/roles/custom_domains/tasks/main.yml, playbooks/roles/edx_ansible/defaults/main.yml, playbooks/roles/edx_ansible/tasks/deploy.yml, playbooks/roles/edx_ansible/templates/app_nodes_inventory.j2, playbooks/roles/edx_ansible/templates/server_vars.j2, playbooks/roles/nginx/defaults/main.yml, playbooks/roles/nginx/tasks/main.yml, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms-common-settings.j2, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms-custom.j2
- Adds letsencrypt role
- Adds appsembler roles and inventory
- We require our own roles repo for the playbook to run.
Especially if we're running "ansible-playbook --tags=letsencrypt:run ..."
in an automated fashion.
- We also need a list of edx app nodes so we copy over a inventory file
called "app_nodes_inventory" that lives in the "edx_ansible_app_dir".
- Putting that all together the calling command should be:
"cd /edx/app/edx_ansible/edx_ansible/playbooks"
"../../venvs/edx_ansible/bin/ansible-playbook -i ../../app_nodes_inventory --tags=letsencrypt:run
amc.yml"
Or something similar depending on what we decide is best but we need to
take care to invoke the correct venv and to be careful with the paths.
- Adds cert_agent role
- Adds tag for getting list of custom domains
- Adds …
=> Adds custom domains support for tahoe

playbooks/amc.yml, playbooks/roles/nginx/defaults/main.yml, playbooks/roles/nginx/tasks/main.yml, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
Needed because let’s encrypt requires default_site on http if present. It seems to me that this doesn't break previous customer deployments, but allows correct behavior if both `lms`
and `letsencrypt` are specified in `nginx_default_sites`.
Also, this PR is paired with the PR on the roles repo: https://github.com/appsembler/roles/pull/20
---
=> Separate default_site option for http and https sites

playbooks/appsemblerPlaybooks/update_theme.yml, playbooks/roles/edxapp/defaults/main.yml, playbooks/roles/edxapp/tasks/customer_theme.yml, playbooks/roles/edxapp/tasks/deploy.yml
use EDXAPP_SITE_THEMES hash to support multiple base/customer themes for Sites
default is defined which will use values from older-style
theme definitions using EDXAPP_DEFAULT_SITE_THEME,
EDXAPP_COMPREHENSIVE_THEME_SOURCE_REPO, and
EDXAPP_COMPREHENSIVE_THEME_VERSION variables.
EDXAPP_SITE_THEMES won't do anything unless comprehensive theming
is enabled
This brings feature from Eucalyptus into Ficus, and also has some DRY changes in `update_theme.yml` and `customer_theme.yml` files
Soon I will be updating base settings files in `edx-configs` to make use of this feature... in the mean time, for an example see Trinity example at https://github.com/noderabbit-team/edx-configs/blob/master/trinity/prod/files/server-vars.yml#L238-L262
=> multiple edxapp Site themes

playbooks/roles/edx_ansible/templates/server_vars.j2
Adds a necessary variable (for Tahoe custom domains to work) to the server-vars.yml that's generated on the services node where the letsencrypt playbook is being run. Without this, the [proper nginx configs](https://github.com/appsembler/configuration/blob/appsembler/ficus/master/playbooks/roles/nginx/tasks/main.yml#L256) don't get copied and the custom domain doesn't work.
---
=> Add needed var to custom domains server-vars.yml file

playbooks/roles/edxapp/tasks/deploy.yml
Amir tried to up a customer using the `install:app-requirements` tag and it failed to update the private_requirements packages because the deployment didn't create the `edxapp-git-identify` file.
This PR adds `install:app-requirements` to the tasks that creates and deletes `edxapp-git-identity`
I tested it on piglet and it seems to work, but I do have concerns that some tasks may not get run, like migrations and restarting apps. Also, looks like `install:app-requirements` does not rebuild assets. Some updates will require asset compilation, which as a manual step can be easily forgotten
=> Added tags to run git identity file tasks when running tag 'install:app-requirements'

playbooks/roles/nginx/defaults/main.yml
Make a new `server-maintenance.html` page and redirect 502, 504 errors (gateway timeout, connection refused) errors to it, rather than showing default server error page.
=> Nginx redirect 502,504 errors to new server-maintenance.html page

playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms-custom.j2
For more information please refer to https://github.com/appsembler/roles/pull/32
---
=> add the option to specify a diferent path for Acme challenge in Nginx config

playbooks/roles/scorm/defaults/main.yml, playbooks/roles/scorm/templates/sync-scorm-content-to-s3.j2
Break up SCORM-to-s3 syncs to go one directory at a time.  Syncing NYIF's was causing out of memory errors.  Also disable error notification emails by default, since they rely on mail software on the server.
=> Sync SCORM files to S3 little by little to avoid out of memory errors

playbooks/appsemblerPlaybooks/update_custom_requirements.yml
3 of the tasks were never running.  I fixed the conditionals for the migrate and restart `edxapp:` and `edxapp_workers:` tasks.  Tags are set up now with the idea that `migrate` can be run if desired (but will not run unless you have set `migrate_db: true` in your server-vars)  and `collect_static_assets` tag is there mostly to exclude that tag if desired (you know that no static assets are contained or changed in your change to the custom requirements).  The other tags were not really necessary as this is a standalone playbook.
=> Fix supervisor tasks and improve tag usage

playbooks/roles/scorm/tasks/main.yml, playbooks/roles/scorm/tasks/scorm_base.yml, playbooks/roles/scorm/templates/nginx_extra_templates/scorm_extra_locations_lms.j2
* small fixes so role can be run independently with run_role.yml again, found it was only working as part of a full deploy playbook.
* make sure /media/scorm location in Nginx LMS config takes precedence over plain /media/ location
* if ScormXBlock configured with SCORM_MEDIA_NO_CACHE set to true, set  `cache-control: no-store` : this is needed at least for now until the XBlock and integration support versioning.
=> Fixups to SCORM role and cache-control no-store option for SCORM media assets

playbooks/roles/nginx/defaults/main.yml, playbooks/roles/nginx/tasks/main.yml, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
Creates a `server-maintenance.html` page by templates, sets it for use on 503 errors.
Allows enabling (default False of course) of a local maintenance mode (edX uses an S3 setup which is cumbersome across many deploys). When activated (run Ansible `nginx:maintenance` tag with `NGINX_EDXAPP_ENABLE_LOCAL_MAINTENANCE` set to true), all requests proxied to LMS and CMS will return a 503 and show the maintenance page.
This incorporates and builds on the Ficus maintenance-mode feature.  Next PR is to extend for Ficus (for Ficus -> later upgrades).
=> Maintenance mode for Ginkgo
